<a href="https://colab.research.google.com/github/sharmin6630/Python-for-Everybody/blob/master/Getting%20Started%20with%20Python/python_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**3.1**
```
Write a program to prompt the user for hours and rate per hour using raw_input to compute gross pay. Pay the hourly rate for
the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour
to test the program (the pay should be 498.75). You should use raw_input to read a string and float() to convert the string to a
number. Do not worry about error checking the user input - assume the user types numbers properly.
```

In [3]:
hrs = float(input("Enter Hours: "))
rat = float(input("Enter Rate: "))
if hrs > 40 :
  pay = (hrs - 40) * 1.5 * rat + 40 * rat
else:
  pay = hrs * rat
print(pay)

# Desired Output:
# 498.75

Enter Hours:45
Enter Rate:10.50
498.75


**3.3**
```
Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is
between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.
```



In [7]:
score = float(input("Enter a score: "))
str = "ABCDEF"
if score < 0 or score > 1.0 :
  print("Error: Score out of range")
if score >= 0.9 :
  print(str[0])
elif score >= 0.8 :
  print(str[1])
elif score >= 0.7 :
  print(str[2])
elif score >= 0.6 :
  print(str[3])
else : 
  print(str[4])

# Desired Output:
# B


Enter a score:0.85
B


**4.6**
```
Write a program to prompt the user for hours and rate per hour using raw_input to compute gross pay. Award time-and-a-half
for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of time-and-a-half in a function
called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of
10.50 per hour to test the program (the pay should be 498.75). You should use raw_input to read a string and float() to convert
the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types
numbers properly.
```

In [12]:
def computepay(h,r) :
  if h > 40 :
    return (h - 40) * r * 1.5 + 40 * r
  else :
    return h * r

hrs = float(input("Enter Hours: "))
rat = float(input("Enter rate: "))
pay = computepay(hrs, rat)
print(pay)
    
# Desired Output
# 498.75

Enter Hours: 45
Enter rate: 10.50
498.75


**5.2**


```
Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered,
print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try
/except and put out an appropriate message and ignore the number. Enter the numbers from the book for problem 5.1 and Match the
desired output as shown.

Enter a number: 4
Enter a number: 5
Enter a number: bad data
Invalid input
Enter a number: 7
Enter a number: done

```



In [11]:
largest = None
smallest = None
while True:
    num = input("Enter a number: ")
    if num == "done" : 
      break
    try:
        num = int(num)
    except:
        print("Invalid input")
        continue
    if smallest is None or smallest > num :
        smallest = num
    if largest is None or largest < num :
        largest = num

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 4
Enter a number: 5
Enter a number: bad data
Invalid input
Enter a number: 7
Enter a number: done
Maximum is 7
Minimum is 4
